"use client";
import { useState } from "react";
const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
const fields=["impressions","reach","likes","comments","shares","saves","clicks"];
export default function AutomationPage(){
 const [m,setM]=useState<Record<string,string>>({}); const [a,setA]=useState<any>(null); const [r,setR]=useState<any>(null); const [s,setS]=useState<any>(null); const [busy,setBusy]=useState(false);
 const calc=async()=>{setBusy(true);const f=new FormData();fields.forEach(k=>f.append(k,m[k]||"0"));try{const x=await fetch(`${API_URL}/api/v1/analytics`,{method:"POST",body:f});const d=await x.json();setA(d);const y=await fetch(`${API_URL}/api/v1/analytics/recommendation`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(d)});setR(await y.json());}finally{setBusy(false)}};
 const schedule=async()=>{const x=await fetch(`${API_URL}/api/v1/automation/schedule`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({calendar_item:{date:new Date().toISOString().slice(0,10),content_type:"Reel",title:"Product spotlight",concept:"Show the product and its strongest benefit."},scheduled_at:new Date().toISOString()})});if(x.ok)setS(await x.json())};
 return <main style={{maxWidth:900,margin:"50px auto",padding:24,fontFamily:"system-ui"}}><a href="/">← Back to ContentForge</a><h1>Automation & Analytics <small>V5</small></h1><p>Measure content performance and prepare posts for a scheduling workflow.</p><section style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:14}}>{fields.map(k=><label key={k} style={{display:"grid",gap:6}}>{k}<input type="number" min="0" value={m[k]||""} onChange={e=>setM({...m,[k]:e.target.value})} placeholder="0" style={{padding:10,border:"1px solid #ddd",borderRadius:8}}/></label>)}</section><div style={{display:"flex",gap:10,margin:"20px 0"}}><button onClick={calc} disabled={busy} style={{padding:"11px 16px"}}>{busy?"Calculating…":"Calculate performance"}</button><button onClick={schedule} style={{padding:"11px 16px"}}>Create schedule item</button></div>{a&&<section style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:12}}>{[[`${a.engagement_rate}%`,`Engagement rate`],[`${a.click_rate}%`,`Click rate`],[a.engagements,"Engagements"]].map(([v,t])=><div key={t as string} style={{padding:18,border:"1px solid #ddd",borderRadius:12}}><b style={{fontSize:28}}>{v}</b><div>{t}</div></div>)}</section>}{r&&<section style={{marginTop:18,padding:18,border:"1px solid #ddd",borderRadius:12}}><b>Performance signal: {r.signal}</b><p>{r.recommendation}</p></section>}{s&&<section style={{marginTop:18,padding:18,border:"1px solid #ddd",borderRadius:12}}><b>Schedule record created</b><p>{s.status} · {s.scheduled_at}</p><small>Direct social publishing is intentionally not claimed here; it requires an approved platform connection and credentials.</small></section>}</main>;
}
