"use client";
import { useEffect, useState } from "react";
const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
const providers=["Instagram","Facebook","YouTube","LinkedIn","X"];
export default function ConnectionsPage(){
 const [items,setItems]=useState<any[]>([]); const [provider,setProvider]=useState(providers[0]); const [account,setAccount]=useState(""); const [token,setToken]=useState(""); const [result,setResult]=useState<any>(null);
 const load=async()=>{const r=await fetch(`${API_URL}/api/v1/connections`); if(r.ok)setItems(await r.json())};
 useEffect(()=>{load()},[]);
 const connect=async()=>{const f=new FormData();f.append("provider",provider);f.append("account_name",account);f.append("token",token);const r=await fetch(`${API_URL}/api/v1/connections`,{method:"POST",body:f});const d=await r.json();if(r.ok){setResult(d);setToken("");await load()}else setResult(d)};
 const dryRun=async()=>{const content={caption:"A sample business update",hashtags:["#smallbusiness"],cta:"Learn more"};const f=new FormData();f.append("provider",provider);f.append("account_name",account||"Demo account");f.append("content",JSON.stringify(content));f.append("dry_run","true");const r=await fetch(`${API_URL}/api/v1/publish`,{method:"POST",body:f});setResult(await r.json())};
 const remove=async(id:number)=>{await fetch(`${API_URL}/api/v1/connections/${id}`,{method:"DELETE"});await load()};
 return <main style={{maxWidth:900,margin:"40px auto",padding:24,fontFamily:"system-ui"}}><a href="/">← Back</a><h1>Account Connections <small>V8</small></h1><p>Secure connection records and a safe publishing pipeline. Live platform publishing is not enabled yet.</p><section style={{padding:20,border:"1px solid #ddd",borderRadius:14,display:"grid",gap:12}}><h2>Connect account</h2><select value={provider} onChange={e=>setProvider(e.target.value)} style={{padding:10}}>{providers.map(p=><option key={p}>{p}</option>)}</select><input value={account} onChange={e=>setAccount(e.target.value)} placeholder="Account / channel name" style={{padding:10}}/><input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="Authorization token (never displayed back)" style={{padding:10}}/><button onClick={connect} disabled={!account||!token} style={{padding:11}}>Save connection</button></section><section style={{marginTop:20}}><h2>Saved connections</h2>{items.length===0?<p>No connections yet.</p>:items.map(x=><div key={x.id} style={{padding:14,border:"1px solid #ddd",borderRadius:10,marginBottom:8,display:"flex",justifyContent:"space-between"}}><span><b>{x.provider}</b> · {x.account_name} · {x.status}</span><button onClick={()=>remove(x.id)}>Disconnect</button></div>)}</section><section style={{marginTop:20,padding:20,border:"1px solid #ddd",borderRadius:14}}><h2>Test publisher</h2><p>This sends no request to a social platform.</p><button onClick={dryRun} style={{padding:11}}>Run safe dry-run</button>{result&&<pre style={{whiteSpace:"pre-wrap",marginTop:14}}>{JSON.stringify(result,null,2)}</pre>}</section></main>;
}
