"use client";

import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import { toPng } from "html-to-image";

const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";

type Brand = { id: number; business_name: string; business_type: string; tagline: string; primary_color: string; secondary_color: string; accent_color: string; font_family: string; phone: string; location: string; social_handle: string; logo_data: string; created_at: string; updated_at: string };
type Reel = { title: string; hook: string; script: string[]; duration: string };
type Carousel = { title: string; slides: string[] };
type Result = { headline: string; subheadline: string; caption: string; hashtags: string[]; cta: string; design: Record<string, any>; reel_ideas: Reel[]; carousel_ideas: Carousel[]; posting_suggestion: { best_days: string[]; best_time: string; frequency: string; tip: string } };
const initial = { businessType: "", businessName: "", productName: "", offer: "", price: "", location: "", phone: "", additionalInfo: "" };
const emptyBrand = { business_name: "", business_type: "", tagline: "", primary_color: "#171722", secondary_color: "#ffffff", accent_color: "#5146d8", font_family: "Inter", phone: "", location: "", social_handle: "", logo_data: "" };

export default function Home() {
  const [form, setForm] = useState(initial); const [photo, setPhoto] = useState(""); const [result, setResult] = useState<Result | null>(null);
  const [brands, setBrands] = useState<Brand[]>([]); const [brand, setBrand] = useState(emptyBrand); const [selectedBrandId, setSelectedBrandId] = useState("");
  const [loading, setLoading] = useState(false); const [brandLoading, setBrandLoading] = useState(false); const [error, setError] = useState(""); const [brandMessage, setBrandMessage] = useState("");

  async function loadBrands() { try { const r = await fetch(`${API_URL}/api/v1/brands`); if (r.ok) setBrands(await r.json()); } catch {} }
  useEffect(() => { loadBrands(); }, []);
  useEffect(() => () => { if (photo) URL.revokeObjectURL(photo); }, [photo]);
  function update(key: keyof typeof initial, value: string) { setForm((old) => ({ ...old, [key]: value })); }
  function updateBrand(key: keyof typeof emptyBrand, value: string) { setBrand((old) => ({ ...old, [key]: value })); }
  function selectBrand(id: string) { setSelectedBrandId(id); const found = brands.find((b) => String(b.id) === id); if (!found) return; setBrand(found); setForm((old) => ({ ...old, businessName: found.business_name, businessType: found.business_type, phone: found.phone, location: found.location })); }
  function onPhoto(e: ChangeEvent<HTMLInputElement>) { const file = e.target.files?.[0]; if (!file) return; if (photo) URL.revokeObjectURL(photo); setPhoto(URL.createObjectURL(file)); }
  async function onLogo(e: ChangeEvent<HTMLInputElement>) { const file = e.target.files?.[0]; if (!file) return; if (file.size > 1_500_000) { setBrandMessage("Logo must be under 1.5 MB."); return; } const reader = new FileReader(); reader.onload = () => updateBrand("logo_data", String(reader.result)); reader.readAsDataURL(file); }
  async function saveBrand() {
    setBrandLoading(true); setBrandMessage(""); try { const method = selectedBrandId ? "PUT" : "POST"; const url = selectedBrandId ? `${API_URL}/api/v1/brands/${selectedBrandId}` : `${API_URL}/api/v1/brands`; const r = await fetch(url, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(brand) }); if (!r.ok) throw new Error(await r.text()); const saved: Brand = await r.json(); setSelectedBrandId(String(saved.id)); setBrand(saved); setForm((old) => ({ ...old, businessName: saved.business_name, businessType: saved.business_type, phone: saved.phone, location: saved.location })); await loadBrands(); setBrandMessage("Brand profile saved ✓"); } catch (e) { setBrandMessage(e instanceof Error ? e.message : "Could not save brand"); } finally { setBrandLoading(false); }
  }
  async function deleteBrand() { if (!selectedBrandId) return; setBrandLoading(true); try { await fetch(`${API_URL}/api/v1/brands/${selectedBrandId}`, { method: "DELETE" }); setSelectedBrandId(""); setBrand(emptyBrand); await loadBrands(); setBrandMessage("Brand profile deleted"); } finally { setBrandLoading(false); } }
  async function generate(e: FormEvent) {
    e.preventDefault(); setLoading(true); setError(""); try { const data = new FormData(); Object.entries(form).forEach(([key, value]) => data.append(key.replace(/[A-Z]/g, (m) => `_${m.toLowerCase()}`), value));
      if (selectedBrandId) data.append("brand_id", selectedBrandId); data.append("brand_tagline", brand.tagline); data.append("brand_primary_color", brand.primary_color); data.append("brand_secondary_color", brand.secondary_color); data.append("brand_accent_color", brand.accent_color); data.append("brand_font_family", brand.font_family); data.append("brand_social_handle", brand.social_handle); data.append("brand_logo", brand.logo_data);
      const input = document.querySelector<HTMLInputElement>("#photo"); if (input?.files?.[0]) data.append("photo", input.files[0]); const response = await fetch(`${API_URL}/api/v1/generate`, { method: "POST", body: data }); if (!response.ok) throw new Error((await response.text()) || "Generation failed"); setResult(await response.json());
    } catch (err) { setError(err instanceof Error ? err.message : "Something went wrong"); } finally { setLoading(false); }
  }
  async function downloadPost() { const node = document.getElementById("post-preview"); if (!node) return; const dataUrl = await toPng(node, { pixelRatio: 2, cacheBust: true }); const a = document.createElement("a"); a.download = "instagram-post-branded.png"; a.href = dataUrl; a.click(); }
  async function copy(text: string) { await navigator.clipboard.writeText(text); }

  return <main className="shell"><div className="container">
    <header className="topbar"><div className="logo">ContentForge</div><span className="badge">V3 • Brand Studio</span></header>
    <section className="hero"><h1>Your brand. Your content. On repeat.</h1><p>Save your business identity once, then generate social content that keeps your colors, font, tagline and logo consistent.</p></section>
    <section className="card brand-card"><div className="section-head"><div><h2>Brand studio</h2><div className="muted">Create a reusable brand profile for every future post.</div></div><select value={selectedBrandId} onChange={(e) => selectBrand(e.target.value)}><option value="">New brand profile</option>{brands.map((b) => <option key={b.id} value={b.id}>{b.business_name}</option>)}</select></div>
      <div className="brand-grid"><Field label="Business name *" value={brand.business_name} onChange={(v) => updateBrand("business_name", v)} placeholder="Bean & Brew" required /><Field label="Business type *" value={brand.business_type} onChange={(v) => updateBrand("business_type", v)} placeholder="Cafe" required /><Field label="Tagline" value={brand.tagline} onChange={(v) => updateBrand("tagline", v)} placeholder="Made fresh, made happy" /><Field label="Social handle" value={brand.social_handle} onChange={(v) => updateBrand("social_handle", v)} placeholder="@beanandbrew" /></div>
      <div className="brand-grid colors"><ColorField label="Primary" value={brand.primary_color} onChange={(v) => updateBrand("primary_color", v)} /><ColorField label="Secondary" value={brand.secondary_color} onChange={(v) => updateBrand("secondary_color", v)} /><ColorField label="Accent" value={brand.accent_color} onChange={(v) => updateBrand("accent_color", v)} /><div className="field"><label>Font</label><select value={brand.font_family} onChange={(e) => updateBrand("font_family", e.target.value)}>{["Inter", "Arial", "Georgia", "Trebuchet MS", "Verdana"].map((f) => <option key={f}>{f}</option>)}</select></div></div>
      <div className="brand-grid"><Field label="Phone" value={brand.phone} onChange={(v) => updateBrand("phone", v)} placeholder="98765 43210" /><Field label="Location" value={brand.location} onChange={(v) => updateBrand("location", v)} placeholder="Connaught Place" /><div className="field logo-field"><label>Logo (PNG/JPG/WebP, max 1.5 MB)</label><input type="file" accept="image/png,image/jpeg,image/webp" onChange={onLogo} />{brand.logo_data && <img src={brand.logo_data} alt="Logo preview" className="logo-preview" />}</div></div>
      <div className="brand-actions"><button className="primary small" disabled={brandLoading || !brand.business_name || !brand.business_type} onClick={saveBrand}>{brandLoading ? "Saving…" : selectedBrandId ? "Save changes" : "Save brand profile"}</button>{selectedBrandId && <button className="secondary small" disabled={brandLoading} onClick={deleteBrand}>Delete profile</button>}{brandMessage && <span className="muted">{brandMessage}</span>}</div>
    </section>
    <div className="grid">
      <section className="card"><h2>Content brief</h2><div className="muted">Add what you want to promote today.</div><form className="form" onSubmit={generate}><div className="row"><Field label="Business type *" value={form.businessType} onChange={(v) => update("businessType", v)} placeholder="e.g. Cafe, Salon, Gym" required /><Field label="Business name" value={form.businessName} onChange={(v) => update("businessName", v)} placeholder="e.g. Bean & Brew" /></div><Field label="Product / service *" value={form.productName} onChange={(v) => update("productName", v)} placeholder="e.g. Cold Coffee" required /><div className="row"><Field label="Offer" value={form.offer} onChange={(v) => update("offer", v)} placeholder="e.g. Buy 1 Get 1" /><Field label="Price" value={form.price} onChange={(v) => update("price", v)} placeholder="e.g. ₹149" /></div><div className="row"><Field label="Location" value={form.location} onChange={(v) => update("location", v)} placeholder="e.g. Connaught Place" /><Field label="Phone" value={form.phone} onChange={(v) => update("phone", v)} placeholder="e.g. 98765 43210" /></div><div className="field"><label>Extra information</label><textarea value={form.additionalInfo} onChange={(e) => update("additionalInfo", e.target.value)} placeholder="Opening hours, special details, delivery info..." /></div><div className="field"><label>Product photo</label><div className="upload"><input id="photo" type="file" accept="image/png,image/jpeg,image/webp" onChange={onPhoto} /></div></div>{error && <div className="error">{error}</div>}<button className="primary" disabled={loading || !form.businessType || !form.productName}>{loading ? "Creating your content…" : "✨ Generate V3 Content"}</button></form></section>
      <section className="card"><h2>Branded post preview</h2><div className="muted">Your saved brand identity is applied automatically.</div><div className="preview-wrap" style={{ marginTop: 18 }}><div id="post-preview" className="preview" style={{ background: brand.primary_color, fontFamily: brand.font_family }}>{photo && <img src={photo} alt="Product preview" />}<div className="overlay" style={{ background: `linear-gradient(180deg, ${brand.primary_color}22, ${brand.primary_color}dd)` }} />{brand.logo_data && <img className="preview-logo" src={brand.logo_data} alt="Brand logo" />} {result?.design.price && <div className="price" style={{ background: brand.secondary_color, color: brand.primary_color }}>{result.design.price}</div>}<div className="post-copy"><div className="post-brand" style={{ color: brand.accent_color }}>{brand.social_handle || brand.business_name || form.businessName || form.businessType || "Your Business"}</div><h3>{result?.headline || form.offer || form.productName || "Your next post"}</h3><p>{result?.subheadline || brand.tagline || "Your offer, ready for Instagram."}</p></div></div></div>{result && <div className="results"><div className="actions"><button className="secondary" onClick={downloadPost}>Download PNG</button><button className="secondary" onClick={() => copy(result.caption)}>Copy caption</button></div><div className="result-box"><strong>Caption</strong><p>{result.caption}</p></div><div className="result-box"><strong>Hashtags</strong><div className="tags">{result.hashtags.map((tag) => <span className="tag" key={tag} style={{ color: brand.accent_color }}>{tag}</span>)}</div></div></div>}</section>
    </div>
    {result && <section className="card" style={{ marginTop: 22 }}><h2>V2 content ideas</h2><div className="muted">Your V2 reels and carousels remain available.</div><div className="results"><div className="result-box"><strong>Reel ideas</strong>{result.reel_ideas.map((r) => <article key={r.title} style={{ marginBottom: 17 }}><p><b>{r.title}</b> · {r.duration}</p><p>Hook: {r.hook}</p><ol>{r.script.map((line, i) => <li key={i}>{line}</li>)}</ol></article>)}</div><div className="result-box"><strong>Carousel ideas</strong>{result.carousel_ideas.map((c) => <article key={c.title} style={{ marginBottom: 14 }}><p><b>{c.title}</b></p><ol>{c.slides.map((s, i) => <li key={i}>{s}</li>)}</ol></article>)}</div><div className="result-box"><strong>Posting suggestion</strong><p><b>{result.posting_suggestion.frequency}</b> · {result.posting_suggestion.best_time}</p><p>Best days: {result.posting_suggestion.best_days.join(", ")}</p><p>{result.posting_suggestion.tip}</p></div></div></section>}
  </div></main>;
}
function Field({ label, value, onChange, placeholder, required }: { label: string; value: string; onChange: (v: string) => void; placeholder: string; required?: boolean }) { return <div className="field"><label>{label}</label><input required={required} value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} /></div>; }
function ColorField({ label, value, onChange }: { label: string; value: string; onChange: (v: string) => void }) { return <div className="field"><label>{label} color</label><div className="color-control"><input type="color" value={/^#[0-9a-fA-F]{6}$/.test(value) ? value : "#171722"} onChange={(e) => onChange(e.target.value)} /><input value={value} onChange={(e) => onChange(e.target.value)} /></div></div>; }
