"use client";
import { useState } from "react";
const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
const platforms = ["Instagram", "Facebook", "YouTube Shorts", "LinkedIn", "X"];
export default function PlatformsPage(){
 const [business,setBusiness]=useState(""); const [topic,setTopic]=useState(""); const [caption,setCaption]=useState(""); const [selected,setSelected]=useState(platforms); const [result,setResult]=useState<any>(null); const [busy,setBusy]=useState(false);
 const toggle=(p:string)=>setSelected(selected.includes(p)?selected.filter(x=>x!==p):[...selected,p]);
 const generate=async()=>{setBusy(true);const f=new FormData();f.append("business_name",business);f.append("topic",topic);f.append("base_caption",caption);f.append("platform_list",selected.join(","));try{const r=await fetch(`${API_URL}/api/v1/platforms`,{method:"POST",body:f});setResult(await r.json())}finally{setBusy(false)}};
 return <main style={{maxWidth:1000,margin:"40px auto",padding:24,fontFamily:"system-ui"}}><a href="/">← Back to ContentForge</a><h1>Multi-Platform Content Engine <small>V7</small></h1><p>Turn one business idea into platform-specific copy and formats.</p><div style={{display:"grid",gap:12,maxWidth:700}}><input placeholder="Business name" value={business} onChange={e=>setBusiness(e.target.value)} style={{padding:12}}/><input placeholder="Topic / campaign" value={topic} onChange={e=>setTopic(e.target.value)} style={{padding:12}}/><textarea placeholder="Optional base caption" value={caption} onChange={e=>setCaption(e.target.value)} style={{padding:12,minHeight:100}}/><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{platforms.map(p=><button key={p} onClick={()=>toggle(p)} style={{padding:"8px 12px",fontWeight:selected.includes(p)?700:400}}>{selected.includes(p)?"✓ ":""}{p}</button>)}</div><button onClick={generate} disabled={busy||!business||!topic||!selected.length} style={{padding:12}}>{busy?"Generating…":"Generate platform content"}</button></div>{result?.platforms&&<section style={{marginTop:28,display:"grid",gap:16}}>{Object.entries(result.platforms).map(([p,v]:any)=><article key={p} style={{border:"1px solid #ddd",borderRadius:14,padding:18}}><h2>{p}</h2><b>{v.format}</b><p style={{whiteSpace:"pre-wrap"}}>{v.caption||v.description||v.text}</p>{v.title&&<p><strong>Title:</strong> {v.title}</p>}<p>{(v.hashtags||[]).join(" ")}</p><strong>CTA:</strong> {v.cta}</article>)}</section>}</main>;
}
